const US_STATES = [
	{ id: 0, full_name: "Alabama", abbr: "AL" },
	{ id: 1, full_name: "Alaska", abbr: "AK" },
	{ id: 2, full_name: "Arizona", abbr: "AZ" },
	{ id: 3, full_name: "Arkansas", abbr: "AR" },
	{ id: 4, full_name: "California", abbr: "CA" },
	{ id: 5, full_name: "Colorado", abbr: "CO" },
	{ id: 6, full_name: "Connecticut", abbr: "CT" },
	{ id: 7, full_name: "Delaware", abbr: "DE" },
	{ id: 8, full_name: "District of Columbia", abbr: "DC" },
	{ id: 9, full_name: "Florida", abbr: "FL" },
	{ id: 10, full_name: "Georgia", abbr: "GA" },
	{ id: 11, full_name: "Hawaii", abbr: "HI" },
	{ id: 12, full_name: "Idaho", abbr: "ID" },
	{ id: 13, full_name: "Illinois", abbr: "IL" },
	{ id: 14, full_name: "Indiana", abbr: "IN" },
	{ id: 15, full_name: "Iowa", abbr: "IA" },
	{ id: 16, full_name: "Kansas", abbr: "KS" },
	{ id: 17, full_name: "Kentucky", abbr: "KY" },
	{ id: 18, full_name: "Louisiana", abbr: "LA" },
	{ id: 19, full_name: "Maine", abbr: "ME" },
	{ id: 20, full_name: "Maryland", abbr: "MD" },
	{ id: 21, full_name: "Massachusetts", abbr: "MA" },
	{ id: 22, full_name: "Michigan", abbr: "MI" },
	{ id: 23, full_name: "Minnesota", abbr: "MN" },
	{ id: 24, full_name: "Mississippi", abbr: "MS" },
	{ id: 25, full_name: "Missouri", abbr: "MO" },
	{ id: 26, full_name: "Montana", abbr: "MT" },
	{ id: 27, full_name: "Nebraska", abbr: "NE" },
	{ id: 28, full_name: "Nevada", abbr: "NV" },
	{ id: 29, full_name: "New Hampshire", abbr: "NH" },
	{ id: 30, full_name: "New Jersey", abbr: "NJ" },
	{ id: 31, full_name: "New Mexico", abbr: "NM" },
	{ id: 32, full_name: "New York", abbr: "NY" },
	{ id: 33, full_name: "North Carolina", abbr: "NC" },
	{ id: 34, full_name: "North Dakota", abbr: "ND" },
	{ id: 35, full_name: "Ohio", abbr: "OH" },
	{ id: 36, full_name: "Oklahoma", abbr: "OK" },
	{ id: 37, full_name: "Oregon", abbr: "OR" },
	{ id: 38, full_name: "Pennsylvania", abbr: "PA" },
	{ id: 39, full_name: "Rhode Island", abbr: "RI" },
	{ id: 40, full_name: "South Carolina", abbr: "SC" },
	{ id: 41, full_name: "South Dakota", abbr: "SD" },
	{ id: 42, full_name: "Tennessee", abbr: "TN" },
	{ id: 43, full_name: "Texas", abbr: "TX" },
	{ id: 44, full_name: "Utah", abbr: "UT" },
	{ id: 45, full_name: "Vermont", abbr: "VT" },
	{ id: 46, full_name: "Virginia", abbr: "VA" },
	{ id: 47, full_name: "Washington", abbr: "WA" },
	{ id: 48, full_name: "West Virginia", abbr: "WV" },
	{ id: 49, full_name: "Wisconsin", abbr: "WI" },
	{ id: 50, full_name: "Wyoming", abbr: "WY" },
];

export { US_STATES };
